# Default Rules Configuration for Developer Mesh
# This file demonstrates production rule configuration

# Task assignment rules
- name: task_assignment_priority
  category: assignment
  expression: "priority >= 3"
  priority: 1
  enabled: true
  metadata:
    description: "High priority tasks require immediate assignment"
    severity: high
    
- name: agent_workload_limit
  category: assignment
  expression: "workload < 10"
  priority: 2
  enabled: true
  metadata:
    description: "Agents should not exceed 10 concurrent tasks"
    threshold: 10
    
- name: task_timeout_check
  category: task_lifecycle
  expression: "elapsed_time > timeout"
  priority: 3
  enabled: true
  metadata:
    description: "Check if task has exceeded its timeout"
    action: alert
    
# Agent management rules
- name: agent_idle_detection
  category: agent_lifecycle
  expression: "idle_time > 300 && status == 'active'"
  priority: 4
  enabled: true
  metadata:
    description: "Detect agents idle for more than 5 minutes"
    idle_threshold_seconds: 300
    
- name: agent_failure_threshold
  category: agent_lifecycle
  expression: "failure_rate > 0.3"
  priority: 5
  enabled: true
  metadata:
    description: "Flag agents with high failure rates"
    failure_threshold: 0.3
    action: review

# Security rules
- name: unauthorized_access_attempt
  category: security
  expression: "auth_failed_count > 3"
  priority: 1
  enabled: true
  metadata:
    description: "Detect multiple failed authentication attempts"
    threshold: 3
    action: block
    
- name: rate_limit_check
  category: security
  expression: "request_rate > 100"
  priority: 2
  enabled: true
  metadata:
    description: "Enforce rate limiting"
    requests_per_minute: 100