# REST API Configuration File
environment: "dev"

api:
  listen_address: ":8080"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
  enable_cors: true
  enable_swagger: true
  auth:
    jwt_secret: "test-jwt-secret"
    api_keys:
      admin: "test-admin-api-key"
      reader: "test-reader-api-key"
  rate_limit: 100
  versioning:
    enabled: true
    default_version: "v1"
    supported_versions: ["v1"]
  performance:
    db_max_idle_conns: 10
    db_max_open_conns: 100
    db_conn_max_lifetime: 30m
    http_max_idle_conns: 100
    http_max_conns_per_host: 10
    http_idle_conn_timeout: 90s
    enable_compression: true
    enable_etag_caching: false
  webhook:
    enabled: true
    github_endpoint: "/api/webhooks/github"
    github_secret: "test-github-webhook-secret"
    github_allowed_events:
      - issues
      - push

server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s

database:
  # Simplified database config for development
  driver: "postgres"
  dsn: "postgresql://dev:dev@database:5432/dev?sslmode=disable&connect_timeout=10&search_path=mcp,public"
  ssl_mode: "disable"
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: 5m
  auto_migrate: false # Temporarily disable migrations for basic startup
  migrations_path: "/app/migrations"

# Add the cache section that the application is looking for
cache:
  type: "redis"
  address: "${REDIS_HOST}:${REDIS_PORT}"
  password: ""
  db: 0
  maxRetries: 3
  minRetryBackoff: 8ms
  maxRetryBackoff: 512ms
  dialTimeout: 5s
  readTimeout: 3s
  writeTimeout: 3s
  poolSize: 10
  minIdleConns: 5

logging:
  level: "info"
  format: "json"
  output: "stdout"

security:
  api_key_header: "X-API-Key"
  default_api_key: "devops-mcp-local-development-key"
  cors:
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["Content-Type", "Authorization", "X-API-Key"]
    expose_headers: ["Content-Length"]
    allow_credentials: true
    max_age: 86400

vector:
  default_model: "text-embedding-ada-002"
  default_dimension: 1536
  default_method: "cosine"
  normalize_vectors: true
