# REST API Docker Configuration
# This provides app-specific overrides for the REST API when running in Docker
# It inherits from the main docker configuration

# Use the main docker configuration as base
_base: ../../configs/config.docker.yaml

# REST API specific settings
api:
  service_name: "rest-api"
  
# REST API might have different rate limits
auth:
  rate_limiting:
    default:
      max_attempts: 500  # Lower rate limit for REST API
      window: 1m
  
# Any REST API-specific overrides can go here
# Most configuration should be in the shared config.docker.yaml