# version: 2
# updates:
#   # Enable version updates for Go modules
#   - package-ecosystem: "gomod"
#     directory: "/apps/mcp-server"
#     schedule:
#       interval: "weekly"
#       day: "monday"
#     open-pull-requests-limit: 5
#     reviewers:
#       - "developer-mesh"
#     labels:
#       - "dependencies"
#       - "go"
#     commit-message:
#       prefix: "chore"
#       include: "scope"

#   - package-ecosystem: "gomod"
#     directory: "/apps/rest-api"
#     schedule:
#       interval: "weekly"
#       day: "monday"
#     open-pull-requests-limit: 5
#     reviewers:
#       - "developer-mesh"
#     labels:
#       - "dependencies"
#       - "go"
#     commit-message:
#       prefix: "chore"
#       include: "scope"

#   - package-ecosystem: "gomod"
#     directory: "/apps/worker"
#     schedule:
#       interval: "weekly"
#       day: "monday"
#     open-pull-requests-limit: 5
#     reviewers:
#       - "developer-mesh"
#     labels:
#       - "dependencies"
#       - "go"
#     commit-message:
#       prefix: "chore"
#       include: "scope"

#   - package-ecosystem: "gomod"
#     directory: "/pkg"
#     schedule:
#       interval: "weekly"
#       day: "monday"
#     open-pull-requests-limit: 5
#     reviewers:
#       - "developer-mesh"
#     labels:
#       - "dependencies"
#       - "go"
#     commit-message:
#       prefix: "chore"
#       include: "scope"

#   # Enable version updates for Docker
#   - package-ecosystem: "docker"
#     directory: "/apps/mcp-server"
#     schedule:
#       interval: "weekly"
#       day: "monday"
#     reviewers:
#       - "developer-mesh"
#     labels:
#       - "dependencies"
#       - "docker"

#   - package-ecosystem: "docker"
#     directory: "/apps/rest-api"
#     schedule:
#       interval: "weekly"
#       day: "monday"
#     reviewers:
#       - "developer-mesh"
#     labels:
#       - "dependencies"
#       - "docker"

#   - package-ecosystem: "docker"
#     directory: "/apps/worker"
#     schedule:
#       interval: "weekly"
#       day: "monday"
#     reviewers:
#       - "developer-mesh"
#     labels:
#       - "dependencies"
#       - "docker"

#   # Enable version updates for GitHub Actions
#   - package-ecosystem: "github-actions"
#     directory: "/"
#     schedule:
#       interval: "weekly"
#       day: "monday"
#     reviewers:
#       - "developer-mesh"
#     labels:
#       - "dependencies"
#       - "github-actions"
