openapi: 3.0.3
info:
  title: Developer Mesh Platform API
  description: |
    The Developer Mesh (Model Context Protocol) Platform is an AI Agent Orchestration Platform that enables intelligent routing and coordination of multiple AI agents for DevOps workflows.
    
    ## Overview
    This API enables:
    - **AI Agent Orchestration**: Register, manage, and coordinate multiple AI agents
    - **Context Management**: Store and retrieve conversation contexts with S3 persistence
    - **Tool Integration**: Execute actions across GitHub, Harness, SonarQube, and more
    - **Multi-Agent Embeddings**: Agent-specific embedding generation with smart provider routing
    - **Cross-Model Search**: Semantic search across embeddings from different models
    - **Binary WebSocket Protocol**: High-performance real-time communication
    - **CRDT Collaboration**: Real-time collaborative features with conflict resolution
    - **Workflow Orchestration**: Multi-step workflows with agent task assignment
    - **Webhook Processing**: Real-time event processing from external services
    
    ## Authentication
    All API requests to /api/v1/* endpoints require authentication via headers:
    - **API Key**: Pass in `Authorization` header as `Bearer <key>` or in `X-API-Key` header
    - **JWT Bearer Token**: Pass as `Bearer <token>` in `Authorization` header
    
    Note: There are no dedicated authentication endpoints. Authentication is handled via middleware
    that validates credentials passed in request headers.
    
    ### Enhanced Security Features
    - Minimum 16-character API keys
    - Configurable failed attempt limits with lockout
    - Scope-based authorization
    - Audit logging for all authentication events
    
    ## Rate Limiting
    - **Default**: 100 requests/minute per identifier
    - **Authentication endpoints**: 5 attempts before 15-minute lockout
    - **Per-tenant limits**: Configurable based on subscription tier
    - **Headers**: X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset
    
  version: 1.0.0
  contact:
    name: Developer Mesh Support
    url: https://github.com/developer-mesh/developer-mesh/issues
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: https://api.dev-mesh.io/api/v1
    description: Production API Server
  - url: http://localhost:8081/api/v1
    description: Local REST API Server
  - url: http://localhost:8080/api/v1
    description: Local MCP Server (WebSocket)

security:
  - ApiKeyAuth: []
  - BearerAuth: []

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
      description: API key authentication (with or without 'Bearer' prefix)
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT bearer token authentication

tags:
  - name: Authentication
    description: Authentication and authorization endpoints
  - name: Health
    description: Health check and monitoring endpoints
  - name: Contexts
    description: MCP context management operations
  - name: Tools
    description: DevOps tool integration endpoints
  - name: Agents
    description: AI agent management and orchestration
  - name: Models
    description: AI model configuration and comparison
  - name: Embeddings
    description: Multi-agent embedding generation and search operations
  - name: Vectors
    description: Vector storage and similarity search
  - name: Search
    description: Semantic and hybrid search endpoints
  - name: Webhooks
    description: Webhook endpoints for external integrations
  - name: GitHub
    description: GitHub-specific tool operations
  - name: Relationships
    description: Entity relationship management
  - name: Workflows
    description: Multi-step workflow orchestration
  - name: Tasks
    description: Task creation and assignment
  - name: Collaboration
    description: Multi-agent collaboration features
  - name: Monitoring
    description: System monitoring and metrics

paths:
  # Health endpoints
  /health:
    $ref: './core/health.yaml#/paths/~1health'
  
  /healthz:
    $ref: './core/health.yaml#/paths/~1healthz'
  
  /readyz:
    $ref: './core/health.yaml#/paths/~1readyz'
  
  /swagger/{any}:
    $ref: './core/health.yaml#/paths/~1swagger~1{any}'
  
  # Context Management
  /contexts:
    $ref: './core/contexts.yaml#/paths/~1contexts'
  
  /contexts/{contextID}:
    $ref: './core/contexts.yaml#/paths/~1contexts~1{contextID}'
  
  /contexts/{contextID}/search:
    $ref: './core/contexts.yaml#/paths/~1contexts~1{contextID}~1search'
  
  /contexts/{contextID}/summary:
    $ref: './core/contexts.yaml#/paths/~1contexts~1{contextID}~1summary'
  
  # Tool Management
  /tools:
    $ref: './core/tools.yaml#/paths/~1tools'
  
  /tools/{tool}:
    $ref: './core/tools.yaml#/paths/~1tools~1{tool}'
  
  /tools/{tool}/actions:
    $ref: './core/tools.yaml#/paths/~1tools~1{tool}~1actions'
  
  /tools/{tool}/actions/{action}:
    $ref: './core/tools.yaml#/paths/~1tools~1{tool}~1actions~1{action}'
  
  /tools/{tool}/queries:
    $ref: './core/tools.yaml#/paths/~1tools~1{tool}~1queries'
  
  
  # Agent Management
  /agents:
    $ref: './core/agents.yaml#/paths/~1agents'
  
  /agents/{id}:
    $ref: './core/agents.yaml#/paths/~1agents~1{id}'
  
  # Model Management
  /models:
    $ref: './core/models.yaml#/paths/~1models'
  
  /models/{id}:
    $ref: './core/models.yaml#/paths/~1models~1{id}'
  
  # Embedding Operations
  /embeddings:
    $ref: './core/embeddings_v2.yaml#/paths/~1embeddings'
  
  /embeddings/batch:
    $ref: './core/embeddings_v2.yaml#/paths/~1embeddings~1batch'
  
  /embeddings/search:
    $ref: './core/embeddings_v2.yaml#/paths/~1embeddings~1search'
  
  /embeddings/search/cross-model:
    $ref: './core/embeddings_v2.yaml#/paths/~1embeddings~1search~1cross-model'
  
  /embeddings/providers/health:
    $ref: './core/embeddings_v2.yaml#/paths/~1embeddings~1providers~1health'
  
  /embeddings/agents:
    $ref: './core/embeddings_v2.yaml#/paths/~1embeddings~1agents'
  
  /embeddings/agents/{agentId}:
    $ref: './core/embeddings_v2.yaml#/paths/~1embeddings~1agents~1{agentId}'
  
  /embeddings/agents/{agentId}/models:
    $ref: './core/embeddings_v2.yaml#/paths/~1embeddings~1agents~1{agentId}~1models'
  
  /embeddings/agents/{agentId}/costs:
    $ref: './core/embeddings_v2.yaml#/paths/~1embeddings~1agents~1{agentId}~1costs'
  
  # Search Operations
  /search:
    $ref: './core/search.yaml#/paths/~1search'
  
  /search/vector:
    $ref: './core/search.yaml#/paths/~1search~1vector'
  
  /search/similar:
    $ref: './core/search.yaml#/paths/~1search~1similar'
  
  
  # Webhook Operations
  /webhooks/github:
    $ref: './core/webhooks.yaml#/paths/~1webhooks~1github'
  
  
  # Relationship Operations
  /relationships:
    $ref: './core/relationships.yaml#/paths/~1relationships'
  
  /relationships/{id}:
    $ref: './core/relationships.yaml#/paths/~1relationships~1{id}'
  
  /entities/{type}/{owner}/{repo}/{id}/relationships:
    $ref: './core/relationships.yaml#/paths/~1entities~1{type}~1{owner}~1{repo}~1{id}~1relationships'
  
  /entities/{type}/{owner}/{repo}/{id}/graph:
    $ref: './core/relationships.yaml#/paths/~1entities~1{type}~1{owner}~1{repo}~1{id}~1graph'
  
  
  
  # Model Extended Operations
  /models/search:
    $ref: './core/models.yaml#/paths/~1models~1search'
  
  # Embedding Extended Operations
  
  # Metrics
  /metrics:
    $ref: './core/metrics.yaml#/paths/~1metrics'
