version: "2"

run:
  timeout: 5m
  skip-dirs:
    - .claude
    - vendor
    - .git

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - unused
    - errcheck

issues:
  exclude-dirs:
    - .claude
    - vendor