# This file configures golangci-lint
# Run with: golangci-lint run

# golangci-lint version configuration
version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - unused
    - errcheck

issues:
  exclude-dirs:
    - .claude
    - vendor
    - .git
    - test/integration