# Minimal golangci-lint configuration
# Disables typecheck due to false positives with mock embedding

run:
  timeout: 10m

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports

issues:
  exclude-use-default: false