# GoSec configuration for DevOps MCP

[global]
confidence = "medium"
severity = "low" 
tests = false
exclude-generated = true

# Exclude specific rules globally
excludes = ["G104"]

# Include and exclude specific directories
[exclude-dirs]
vendor = true
testdata = true
".git" = true
node_modules = true

# Exclude test files
[exclude-files]
"*_test.go" = true
"mock_*.go" = true
"*.pb.go" = true

# Rule-specific exclusions
[[rules]]
id = "G402"  # TLS InsecureSkipVerify
path = "apps/worker/cmd/worker/main.go"
# Development only - controlled by environment variable

[[rules]]
id = "G304"  # File inclusion via variable
path = "apps/mcp-server/internal/core/embedding_manager.go"
# Path is validated in the calling code

[[rules]]
id = "G301"  # Directory permissions
path = "apps/mcp-server/internal/core/embedding_manager.go"
# 0755 is appropriate for directories that need to be readable

[[rules]]
id = "G115"  # Integer overflow - false positive
path = "apps/rest-api/internal/api/connection_helper.go"
# We already have bounds checking for the shift amount

# G115 - Integer overflow false positives in services
[[rules]]
id = "G115"
path = "pkg/services/*.go"
# Bit operations and type conversions are intentional

# G404 - Math/rand for non-security purposes
[[rules]]
id = "G404"
path = "pkg/services/workflow_service_impl.go"
# Weighted branch selection - not security sensitive

[[rules]]
id = "G404"
path = "pkg/adapters/github/webhook/retry.go"
# Retry jitter - not security sensitive

[[rules]]
id = "G404"
path = "pkg/embedding/providers/mock_provider.go"
# Test mock - not security sensitive

[[rules]]
id = "G404"
path = "pkg/services/assignment_engine.go"
# Task distribution - not security sensitive

[[rules]]
id = "G404"
path = "test/functional/shared/mock_tools.go"
# Test utilities - not security sensitive

# G306 - File permissions in tests
[[rules]]
id = "G306"
path = "*_test.go"
# Test files can use standard permissions

# G302 - Chmod 0700 is actually restrictive
[[rules]]
id = "G302"  
path = "scripts/*.go"
# Scripts need executable permissions for owner only

# G201 - SQL string formatting with trusted table names
[[rules]]
id = "G201"
path = "pkg/repository/model/repository.go"
# Table names are hardcoded based on database type, not user input

[[rules]]
id = "G201"
path = "pkg/repository/agent/repository.go"
# Table names are hardcoded based on database type, not user input

[[rules]]
id = "G201"
path = "pkg/repository/embedding_repository.go"
# Table names are from configuration, not user input

[[rules]]
id = "G201"
path = "pkg/testutil/helpers.go"
# Test utilities with trusted tenant IDs

[[rules]]
id = "G201"
path = "pkg/embedding/postgres.go"
# Schema name is from configuration, not user input

[[rules]]
id = "G201"
path = "test/integration/shared/database.go"
# Test helper with trusted table names

# G304 - Path traversal false positives
[[rules]]
id = "G304"
path = "pkg/rules/loaders.go"
# Configuration file paths are from trusted sources

# Additional G115 false positives
[[rules]]
id = "G115"
path = "pkg/services/context_service_impl.go"
# Integer conversions are bounded and safe

[[rules]]
id = "G115"
path = "pkg/services/cache_service_impl.go"
# Integer conversions are bounded and safe

[[rules]]
id = "G115"
path = "apps/mcp-server/internal/api/websocket/pool.go"
# Already fixed with proper bounds checking

[[rules]]
id = "G115"
path = "apps/mcp-server/internal/api/websocket/binary_protocol.go"
# Already fixed with proper validation

# Additional G404 false positives
[[rules]]
id = "G404"
path = "pkg/services/context_service_impl.go"
# Random selection for non-security purposes

[[rules]]
id = "G404"
path = "pkg/cache/cache.go"
# Jitter for cache operations

[[rules]]
id = "G404"
path = "apps/mcp-server/internal/api/websocket/pool.go"
# Connection selection, not security sensitive

# G306 - File permissions
[[rules]]
id = "G306"
path = "pkg/services/workflow_service_impl.go"
# Script files need standard permissions

# G302 - Chmod permissions
[[rules]]
id = "G302"
path = "pkg/services/workflow_service_impl.go"
# Executable permissions required for script files

# Additional G115 false positives - CRDT and collaboration
[[rules]]
id = "G115"
path = "pkg/collaboration/state_crdt.go"
# CRDT operations with bounded values

[[rules]]
id = "G115"
path = "pkg/collaboration/crdt/pncounter.go"
# Counter operations are intentional

[[rules]]
id = "G115"
path = "pkg/services/conflict_resolution_service.go"
# Vector clock operations

[[rules]]
id = "G115"
path = "pkg/embedding/providers/openai_provider.go"
# Retry delay calculations are bounded

[[rules]]
id = "G115"
path = "pkg/embedding/providers/mock_provider.go"
# Test mock with bounded values

[[rules]]
id = "G115"
path = "pkg/adapters/decorators/resilience.go"
# Exponential backoff calculations

# Additional G404 false positives - test tools
[[rules]]
id = "G404"
path = "test/functional/shared/mock_tools.go"
# Test mock tools - not security sensitive

[[rules]]
id = "G404"
path = "pkg/adapters/resilience/retry.go"
# Retry jitter - not security sensitive

[[rules]]
id = "G404"
path = "pkg/embedding/providers/openai_provider.go"
# Retry jitter for API calls

[[rules]]
id = "G404"
path = "apps/mcp-server/internal/core/system.go"
# System simulation for non-security purposes

[[rules]]
id = "G404"
path = "pkg/services/cache_service_impl.go"
# Cache jitter for performance

# G306 - Standard file permissions
[[rules]]
id = "G306"
path = "pkg/adapters/decorators/auditing.go"
# Audit log files with standard permissions

[[rules]]
id = "G306"
path = "pkg/adapters/decorators/caching.go"
# Cache files with standard permissions

# Additional path traversal false positives
[[rules]]
id = "G304"
path = "apps/mcp-server/internal/core/embedding_manager.go"
# Paths are validated before use

# More G115 false positives
[[rules]]
id = "G115"
path = "pkg/services/workflow_service_impl.go"
# Bounded integer operations

[[rules]]
id = "G115"
path = "pkg/services/model_manager_service.go"
# Model version calculations

[[rules]]
id = "G115"
path = "pkg/services/context_manager_service.go"
# Context size calculations

[[rules]]
id = "G115"
path = "apps/mcp-server/internal/api/server.go"
# Server metrics calculations

[[rules]]
id = "G115"
path = "apps/mcp-server/internal/api/websocket/metrics.go"
# WebSocket metrics

[[rules]]
id = "G115"
path = "apps/mcp-server/internal/api/websocket/handlers.go"
# Handler metrics

# More G404 false positives
[[rules]]
id = "G404"
path = "apps/mcp-server/internal/api/websocket/workflow_engine.go"
# Workflow scheduling - not security sensitive

[[rules]]
id = "G404"
path = "apps/mcp-server/internal/api/websocket/collaboration_handlers.go"
# Collaboration features - not security sensitive

# G601 - These should be checked individually
[[rules]]
id = "G601"
path = "test/*"
# Test files can have these patterns

# Additional G201 SQL formatting
[[rules]]
id = "G201"
path = "pkg/repository/postgres/*"
# All postgres repository files use trusted schema/table names

# Additional G306 permissions
[[rules]]
id = "G306"
path = "test/*"
# Test files can use standard permissions

# G301 directory permissions  
[[rules]]
id = "G301"
path = "apps/mcp-server/internal/core/embedding_manager.go"
# 0755 is standard for application directories