# GoSec configuration for DevOps MCP

[global]
confidence = "medium"
severity = "low" 
tests = false
exclude-generated = true

# Exclude specific rules globally
excludes = ["G104"]

# Include and exclude specific directories
[exclude-dirs]
vendor = true
testdata = true
".git" = true
node_modules = true

# Exclude test files
[exclude-files]
"*_test.go" = true
"mock_*.go" = true
"*.pb.go" = true