# GoSec configuration for DevOps MCP

[global]
confidence = "medium"
severity = "low" 
tests = false
exclude-generated = true

# Exclude specific rules globally
excludes = ["G104"]

# Include and exclude specific directories
[exclude-dirs]
vendor = true
testdata = true
".git" = true
node_modules = true

# Exclude test files
[exclude-files]
"*_test.go" = true
"mock_*.go" = true
"*.pb.go" = true

# Rule-specific exclusions
[[rules]]
id = "G402"  # TLS InsecureSkipVerify
path = "apps/worker/cmd/worker/main.go"
# Development only - controlled by environment variable

[[rules]]
id = "G304"  # File inclusion via variable
path = "apps/mcp-server/internal/core/embedding_manager.go"
# Path is validated in the calling code

[[rules]]
id = "G301"  # Directory permissions
path = "apps/mcp-server/internal/core/embedding_manager.go"
# 0755 is appropriate for directories that need to be readable

[[rules]]
id = "G115"  # Integer overflow - false positive
path = "apps/rest-api/internal/api/connection_helper.go"
# We already have bounds checking for the shift amount