version: '3.8'

services:
  mcp-server:
    build:
      context: .
      dockerfile: apps/mcp-server/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=development
    depends_on:
      - database
    volumes:
      - ./apps/mcp-server/configs:/app/configs
      
  rest-api:
    build:
      context: .
      dockerfile: apps/rest-api/Dockerfile
    ports:
      - "8081:8080"
    environment:
      - APP_ENV=development
    depends_on:
      - database
    volumes:
      - ./apps/rest-api/configs:/app/configs
      
  worker:
    build:
      context: .
      dockerfile: apps/worker/Dockerfile
    environment:
      - APP_ENV=development
    depends_on:
      - database
      - mcp-server
    volumes:
      - ./apps/worker/configs:/app/configs
  
  database:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
