# Default Policies Configuration for DevOps MCP
# This file demonstrates production policy configuration

# Task lifecycle policy
- name: task_lifecycle
  resource: task
  rules:
    - condition: "status == 'pending'"
      effect: allow
      actions:
        - assign
        - cancel
        - view
      resources:
        - "task:*"
    - condition: "status == 'in_progress'"
      effect: allow
      actions:
        - update
        - complete
        - fail
        - view
      resources:
        - "task:*"
    - condition: "status == 'completed' || status == 'failed'"
      effect: deny
      actions:
        - update
        - assign
      resources:
        - "task:*"
  defaults:
    timeout: 3600
    max_retries: 3
    priority: medium
    auto_retry: true

# Agent management policy
- name: agent_management
  resource: agent
  rules:
    - condition: "role == 'admin'"
      effect: allow
      actions:
        - create
        - update
        - delete
        - view
        - configure
      resources:
        - "agent:*"
    - condition: "role == 'operator'"
      effect: allow
      actions:
        - view
        - update
        - start
        - stop
      resources:
        - "agent:*"
    - condition: "role == 'viewer'"
      effect: allow
      actions:
        - view
      resources:
        - "agent:*"
  defaults:
    max_concurrent_tasks: 10
    idle_timeout: 300
    health_check_interval: 60
    auto_restart: true

# Workspace access policy
- name: workspace_access
  resource: workspace
  rules:
    - condition: "is_public == true"
      effect: allow
      actions:
        - read
      resources:
        - "workspace:*"
    - condition: "is_member == true"
      effect: allow
      actions:
        - read
        - update
        - invite
      resources:
        - "workspace:*"
    - condition: "is_owner == true"
      effect: allow
      actions:
        - "*"
      resources:
        - "workspace:*"
  defaults:
    max_members: 100
    retention_days: 90
    default_visibility: private
    backup_enabled: true

# Document collaboration policy
- name: document_collaboration
  resource: document
  rules:
    - condition: "is_locked == true && lock_owner != user_id"
      effect: deny
      actions:
        - update
        - delete
      resources:
        - "document:*"
    - condition: "permission == 'write'"
      effect: allow
      actions:
        - read
        - update
        - lock
        - unlock
      resources:
        - "document:*"
    - condition: "permission == 'read'"
      effect: allow
      actions:
        - read
      resources:
        - "document:*"
  defaults:
    lock_timeout: 900
    auto_save_interval: 30
    version_retention: 50
    conflict_resolution: last_write_wins

# API rate limiting policy
- name: api_rate_limiting
  resource: api
  rules:
    - condition: "user_tier == 'free'"
      effect: allow
      actions:
        - "*"
      resources:
        - "api:*"
      metadata:
        rate_limit: 100
        burst: 20
    - condition: "user_tier == 'pro'"
      effect: allow
      actions:
        - "*"
      resources:
        - "api:*"
      metadata:
        rate_limit: 1000
        burst: 200
    - condition: "user_tier == 'enterprise'"
      effect: allow
      actions:
        - "*"
      resources:
        - "api:*"
      metadata:
        rate_limit: 10000
        burst: 2000
  defaults:
    rate_limit: 100
    burst: 20
    window: 60