apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcp-server
  namespace: default
  annotations:
    # Replace with your own AWS account ID and IAM role name
    eks.amazonaws.com/role-arn: arn:aws:iam::<AWS_ACCOUNT_ID>:role/mcp-server-role
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mcp-server-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: mcp-server
  namespace: default
roleRef:
  kind: Role
  name: mcp-server-role
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mcp-server-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
