# MCP Server Docker Configuration
# This provides app-specific overrides for the MCP server when running in Docker
# It inherits from the main docker configuration

# Use the main docker configuration as base
_base: ../../configs/config.docker.yaml

# MCP Server specific settings
api:
  service_name: "mcp-server"
  
# Any MCP server-specific overrides can go here
# Most configuration should be in the shared config.docker.yaml

# WebSocket specific settings for MCP Server
websocket:
  # Override with MCP-specific settings if needed
  # Connection pooling optimized for MCP protocol
  connection_pool:
    enabled: true
    size: 100
    idle_timeout: 5m
    
  # MCP protocol-specific settings
  protocol:
    version: "1.0"
    subprotocols: ["mcp.v1"]
    
  # Binary protocol settings
  binary:
    enabled: true
    compression: true
    compression_level: 6  # 1-9, 6 is default