# MCP Server Docker Configuration
# This provides app-specific overrides for the MCP server when running in Docker
# It inherits from the main docker configuration

# Use the main docker configuration as base
_base: ../../configs/config.docker.yaml

# MCP Server specific settings
api:
  service_name: "mcp-server"
  
# Any MCP server-specific overrides can go here
# Most configuration should be in the shared config.docker.yaml