ignored:
  - DL3008  # Pin versions in apt-get install
  - DL3009  # Delete the apt-get lists after installing something
  - DL3015  # Avoid additional packages by specifying --no-install-recommends

trustedRegistries:
  - docker.io
  - gcr.io
  - ghcr.io
  - golang

override:
  error:
    - DL3000  # Use absolute WORKDIR
    - DL3002  # Last USER should not be root
    - DL3003  # Use WORKDIR to switch to a directory
    - DL3004  # Do not use sudo
    - DL3011  # Valid UNIX ports range from 0 to 65535
    - DL3021  # COPY with more than 2 arguments requires the last argument to end with /
    - DL3030  # Use the -y switch to avoid manual input
    - DL3032  # yum clean all is not supported
  warning:
    - DL3001  # For some bash commands it makes no sense running them in a Docker container
    - DL3007  # Using latest is prone to errors if the image will ever update
    - DL3018  # Pin versions in apk add
    - DL3019  # Use the --no-cache switch to avoid the need to use --update
    - DL3028  # Pin versions in gem install
  info:
    - DL3025  # Use arguments JSON notation for CMD and ENTRYPOINT arguments
    - DL3029  # Do not use --platform flag with FROM

label-schema:
  author: email
  contact: email
  created: rfc3339
  version: semver
  documentation: url
  source: url
  url: url
  vcs-url: url
  vendor: text
  description: text
  maintainer: email