auth:
  development_keys:
    test_admin:
      role: admin
      scopes: ["read", "write", "admin"]
      tenant_id: default
      expires_in: 30d
    test_readonly:
      role: read
      scopes: ["read"]
      tenant_id: default
      expires_in: 30d
  production_key_source: env