# Development Configuration
# Inherits from config.base.yaml and overrides for local development

# Import base configuration
_base: config.base.yaml

# Environment
environment: "development"

# API Server - Development overrides
api:
  listen_address: ":8080"
  enable_swagger: true
  enable_pprof: true  # Enable profiling in dev
  
  # CORS - Allow all origins in development
  cors:
    allowed_origins: ["*"]
    
  # Disable auth for easier testing (can be toggled)
  auth:
    require_auth: ${REQUIRE_AUTH:-false}

# Authentication - Development settings
auth:
  # JWT - Short expiration for testing
  jwt:
    secret: "dev-jwt-secret-minimum-32-characters"
    expiration: 1h
    refresh_expiration: 24h
    
  # Development API keys
  api_keys:
    static_keys:
      "dev-admin-key-1234567890": 
        role: "admin"
        scopes: ["read", "write", "admin"]
        tenant_id: "dev-tenant"
      "dev-readonly-key-1234567890":
        role: "reader"
        scopes: ["read"]
        tenant_id: "dev-tenant"
        
  # Relaxed security in dev
  security:
    max_failed_attempts: 10
    lockout_duration: 1m
    
  # Minimal rate limiting in dev
  rate_limiting:
    default:
      max_attempts: 1000
      window: 1m
      
  # Verbose audit logging
  audit:
    log_level: "debug"
    log_to_console: true

# WebSocket - Development settings
websocket:
  enabled: true  # Enable WebSocket in development
  max_connections: 1000  # Lower limit for local development
  
  # Security - Relaxed for development
  security:
    require_auth: false  # Disable auth for easier testing
    hmac_signatures: false
    allowed_origins: ["*"]  # Allow all origins in dev
    
  # Rate limiting - Relaxed for development
  rate_limit:
    rate: 100  # 6000 per minute (100 per second) - higher for testing
    burst: 200
    per_ip: false  # Disable IP-based limiting in dev
    per_user: false  # Disable user-based limiting in dev

# Database - Local PostgreSQL
database:
  host: "${DB_HOST:-localhost}"
  port: ${DB_PORT:-5432}
  username: "${DB_USER:-postgres}"
  password: "${DB_PASSWORD:-postgres}"
  database: "${DB_NAME:-devops_mcp_dev}"
  ssl_mode: "disable"
  
  # Migrations
  migrations:
    auto_migrate: true
    migrations_path: "./migrations"

# Cache - AWS ElastiCache Redis
cache:
  type: "redis"  # Standard Redis (not cluster mode)
  address: "${REDIS_HOST:-sean-mcp-test-qem3fz.serverless.use1.cache.amazonaws.com}:${REDIS_PORT:-6379}"
  password: "${REDIS_PASSWORD:-}"
  database: 0
  
  # Connection settings for AWS ElastiCache
  pool_size: 50
  min_idle_conns: 10
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s
  max_retries: 3
  
  # TLS settings for ElastiCache (if needed)
  tls:
    enabled: ${REDIS_TLS_ENABLED:-false}
    insecure_skip_verify: ${REDIS_TLS_SKIP_VERIFY:-false}

# Monitoring - Development settings
monitoring:
  logging:
    level: "debug"
    format: "text"  # Human-readable in dev
    output: "stdout"
    color: true
    
  metrics:
    enabled: true
    
  tracing:
    enabled: false  # Usually disabled in dev

# Storage - Real AWS S3
storage:
  context:
    provider: "${STORAGE_PROVIDER:-s3}"  # Use S3 by default, can override to filesystem
    filesystem:
      base_path: "./data/contexts"
      
  # Real AWS S3 configuration
  s3:
    endpoint: "${S3_ENDPOINT:-}"  # Empty for real AWS S3
    region: "${AWS_REGION:-us-east-1}"
    bucket: "${S3_BUCKET:-mcp-dev-contexts}"
    force_path_style: false  # Use virtual-hosted-style for real S3
    disable_ssl: false  # Use SSL for real S3
    
    # AWS credentials (from environment or IAM role)
    access_key_id: "${AWS_ACCESS_KEY_ID:-}"
    secret_access_key: "${AWS_SECRET_ACCESS_KEY:-}"
    session_token: "${AWS_SESSION_TOKEN:-}"  # For temporary credentials

# Adapters - Development settings
adapters:
  github:
    token: "${GITHUB_TOKEN:-mock-token}"
    base_url: "${GITHUB_API_URL:-https://api.github.com}"
    webhook_secret: "dev-webhook-secret"
    
    # Use mock server in dev
    mock:
      enabled: ${USE_MOCK_GITHUB:-true}
      url: "http://localhost:8081/mock-github"
      
  # Other adapters with dev settings
  sonarqube:
    base_url: "${SONARQUBE_URL:-http://localhost:9000}"
    token: "${SONARQUBE_TOKEN:-mock-token}"

# Development-specific features
dev:
  # Hot reload
  hot_reload:
    enabled: true
    watch_paths:
      - "./configs"
      - "./internal"
      
  # Seed data
  seed_data:
    enabled: true
    file: "./test/fixtures/seed_data.yaml"
    
  # Debug endpoints
  debug_endpoints:
    enabled: true
    path_prefix: "/__debug"
    
  # Request/Response logging
  http_logging:
    enabled: true
    log_headers: true
    log_body: true
    max_body_log_size: 1024

# Feature flags - Enable experimental features in dev
features:
  experimental_tools: true
  debug_mode: true
  mock_external_services: true

# Embedding Configuration - Development
embedding:
  # Enable at least one provider for development
  providers:
    # OpenAI Provider - Primary for development
    openai:
      enabled: ${OPENAI_ENABLED:-false}
      api_key: "${OPENAI_API_KEY}"
      
    # AWS Bedrock Provider - Real AWS
    bedrock:
      enabled: ${BEDROCK_ENABLED:-true}  # Enable by default for AWS development
      region: "${AWS_REGION:-us-east-1}"
      # Empty endpoint to use real AWS Bedrock
      endpoint: "${BEDROCK_ENDPOINT:-}"
      
      # AWS credentials (from environment or IAM role)
      access_key_id: "${AWS_ACCESS_KEY_ID:-}"
      secret_access_key: "${AWS_SECRET_ACCESS_KEY:-}"
      session_token: "${AWS_SESSION_TOKEN:-}"  # For temporary credentials
      
    # Google AI Provider
    google:
      enabled: ${GOOGLE_AI_ENABLED:-false}
      api_key: "${GOOGLE_AI_API_KEY}"
  
  # Development-friendly defaults
  default_agent_config:
    embedding_strategy: "speed"  # Prioritize speed in dev
    model_preferences:
      primary_models:
        - "text-embedding-3-small"  # Cheaper and faster for dev
      fallback_models:
        - "text-embedding-ada-002"
    constraints:
      max_tokens_per_request: 8000
      max_cost_per_day: 1.0  # Lower cost limit for dev
      preferred_dimensions: 1536
      allow_dimension_reduction: true
  
  # More forgiving circuit breaker in dev
  circuit_breaker:
    failure_threshold: 10
    success_threshold: 1
    timeout: "60s"
    
  # Simpler routing in dev
  router:
    selection_strategy: "round_robin"  # Simple strategy for dev
    cache_ttl: "1m"  # Shorter cache in dev

# Worker Configuration - Real AWS SQS
worker:
  queue_type: "${WORKER_QUEUE_TYPE:-sqs}"  # Use SQS by default
  concurrency: ${WORKER_CONCURRENCY:-10}
  
  # Real AWS SQS configuration
  sqs:
    queue_url: "${SQS_QUEUE_URL:-https://sqs.us-east-1.amazonaws.com/594992249511/sean-mcp-test}"
    region: "${AWS_REGION:-us-east-1}"
    
    # AWS credentials (from environment or IAM role)
    access_key_id: "${AWS_ACCESS_KEY_ID:-}"
    secret_access_key: "${AWS_SECRET_ACCESS_KEY:-}"
    session_token: "${AWS_SESSION_TOKEN:-}"  # For temporary credentials
    
    # SQS settings
    visibility_timeout: 30s
    wait_time_seconds: 20  # Long polling
    max_messages: 10  # Max messages per receive
    
  # Memory queue for local testing without AWS
  memory:
    enabled: ${MEMORY_QUEUE_ENABLED:-false}
    buffer_size: 1000

# AWS Configuration - Common settings for all AWS services
aws:
  region: "${AWS_REGION:-us-east-1}"
  
  # Credentials (optional - can use IAM role or environment)
  credentials:
    access_key_id: "${AWS_ACCESS_KEY_ID:-}"
    secret_access_key: "${AWS_SECRET_ACCESS_KEY:-}"
    session_token: "${AWS_SESSION_TOKEN:-}"
    
  # Service endpoints (empty for real AWS)
  endpoints:
    s3: "${S3_ENDPOINT:-}"
    sqs: "${SQS_ENDPOINT:-}"
    bedrock: "${BEDROCK_ENDPOINT:-}"
    
  # ElastiCache specific configuration
  elasticache:
    endpoint: "${ELASTICACHE_ENDPOINT:-sean-mcp-test-qem3fz.serverless.use1.cache.amazonaws.com:6379}"
    auth_token: "${ELASTICACHE_AUTH_TOKEN:-}"