# Test configuration for MCP Server

server:
  listenAddress: "0.0.0.0:8080"
  readTimeout: 30s
  writeTimeout: 30s
  idleTimeout: 60s
  enableSwagger: true
  enableCORS: true

database:
  driver: "postgres"
  dsn: "${DATABASE_DSN}"
  host: "${POSTGRES_HOST}"
  port: "${POSTGRES_PORT}"
  user: "${POSTGRES_USER}"
  password: "${POSTGRES_PASSWORD}"
  database: "${POSTGRES_DB}"
  sslMode: "disable"
  maxOpenConns: 10
  maxIdleConns: 5
  connMaxLifetime: 1h

cache:
  type: "redis"
  address: "${REDIS_HOST}:${REDIS_PORT}"
  password: ""
  db: 0
  maxRetries: 3
  minRetryBackoff: 8ms
  maxRetryBackoff: 512ms
  dialTimeout: 5s
  readTimeout: 3s
  writeTimeout: 3s
  poolSize: 10
  minIdleConns: 5

auth:
  jwt_secret: "test-jwt-secret"
  api_keys:
    admin: "test-admin-api-key"
    reader: "test-reader-api-key"

logging:
  level: "${LOG_LEVEL}"
  format: "json"
  outputPaths:
    - "stdout"
  errorOutputPaths:
    - "stderr"

tools:
  mockserver:
    baseURL: "${MOCKSERVER_URL}"
    apiKey: "test-mockserver-key"

performance:
  enableCompression: true
  enableETagCaching: false
  httpMaxIdleConns: 100
  httpMaxConnsPerHost: 100
  httpIdleConnTimeout: 90s

versioning:
  defaultVersion: "v1"
  supportedVersions:
    - "v1"

rateLimit:
  enabled: false
  requestsPerSecond: 100
  burst: 50
