# REST API specific configuration
# This file is used when running the REST API service
# It ensures the REST API runs on port 8081 instead of 8080

environment: "${ENVIRONMENT:-production}"

database:
  host: "${DATABASE_HOST}"
  port: ${DATABASE_PORT}
  username: "${DATABASE_USER}"
  password: "${DATABASE_PASSWORD}"
  database: "${DATABASE_NAME}"
  ssl_mode: "${DATABASE_SSL_MODE:-require}"

cache:
  type: "redis"
  address: "${REDIS_ADDR}"
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s
  max_retries: 3
  tls:
    enabled: true
    insecure_skip_verify: true

# REST API specific port configuration
api:
  listen_address: ":8081"
  enable_health_check: true

storage:
  context:
    provider: "s3"
  s3:
    region: "${AWS_REGION}"
    bucket: "${S3_BUCKET}"

auth:
  api_keys:
    static_keys:
      "${ADMIN_API_KEY}":
        role: "admin"
        scopes: ["read", "write", "admin"]

adapters:
  github:
    token: "${GITHUB_TOKEN}"
  aws:
    region: "${AWS_REGION}"
    access_key_id: "${AWS_ACCESS_KEY_ID}"
    secret_access_key: "${AWS_SECRET_ACCESS_KEY}"

worker:
  queue_type: "sqs"
  sqs:
    queue_url: "${SQS_QUEUE_URL}"

monitoring:
  logging:
    level: "info"
    format: "json"