# Staging Configuration
# Inherits from config.base.yaml - Similar to production but with some relaxations

# Import base configuration
_base: config.base.yaml

# Environment
environment: "staging"

# API Server - Staging settings
api:
  listen_address: ":${PORT:-8080}"
  enable_swagger: true   # Enable for testing
  enable_pprof: false
  
  # TLS optional in staging
  tls:
    enabled: ${TLS_ENABLED:-false}
    
  # CORS - Allow testing domains
  cors:
    allowed_origins: 
      - "https://staging.example.com"
      - "https://test.example.com"
      - "${ADDITIONAL_CORS_ORIGINS}"

# Authentication - Staging settings
auth:
  jwt:
    secret: "${JWT_SECRET}"
    expiration: 12h  # Shorter for testing
    
  # Allow some test keys
  api_keys:
    static_keys:
      "${STAGING_TEST_KEY}":
        role: "tester"
        scopes: ["read", "write"]
        tenant_id: "staging-tests"
        
  # Moderate security
  security:
    max_failed_attempts: 10
    lockout_duration: 5m
    
  # Higher rate limits for testing
  rate_limiting:
    default:
      max_attempts: 500
      window: 1m
      
  # Verbose audit for debugging
  audit:
    log_level: "info"
    include_request_body: true

# Database - Staging RDS
database:
  host: "${RDS_HOST}"
  port: 5432
  username: "${RDS_USERNAME}"
  password: "${RDS_PASSWORD}"
  database: "${RDS_DATABASE}"
  ssl_mode: "prefer"
  
  # Smaller pools than production
  max_open_conns: 50
  max_idle_conns: 10
  
  # Enable query logging
  log_queries: ${LOG_QUERIES:-true}
  slow_query_threshold: 100ms

# Cache - Staging Redis
cache:
  distributed:
    address: "${REDIS_HOST}:${REDIS_PORT}"
    password: "${REDIS_PASSWORD}"
    
    # Smaller pools
    pool_size: 50
    
  # Local cache for testing
  local:
    enabled: true
    size: 10000
    ttl: 30s

# Monitoring - Enhanced for staging
monitoring:
  logging:
    level: "${LOG_LEVEL:-info}"
    format: "json"
    
  # Always enable metrics in staging
  metrics:
    enabled: true
    include_method_label: true
    include_status_label: true
    
  # Enable tracing for debugging
  tracing:
    enabled: true
    sample_rate: 1.0  # Trace everything

# Storage - Staging S3
storage:
  s3:
    region: "${AWS_REGION}"
    bucket: "${S3_BUCKET}"
    
    # Staging-specific prefix
    path_prefix: "staging/"
    
    # Less aggressive lifecycle
    lifecycle:
      enabled: true
      archive_after_days: 30
      delete_after_days: 90

# Adapters - Staging endpoints
adapters:
  github:
    # Can use production or sandbox
    base_url: "${GITHUB_API_URL:-https://api.github.com}"
    token: "${GITHUB_TOKEN}"
    
    # Enable retries with logging
    retry:
      enabled: true
      max_attempts: 5
      log_retries: true

# Testing features
testing:
  # Chaos engineering
  chaos:
    enabled: ${CHAOS_ENABLED:-false}
    failure_rate: 0.01
    
  # Load testing endpoints
  load_testing:
    enabled: true
    endpoints:
      - "/api/v1/__load_test"
      
  # Synthetic monitoring
  synthetic:
    enabled: true
    interval: 5m

# Feature flags - More experimental features
features:
  experimental_tools: true
  canary_deployments: true
  a_b_testing: true