# MCP Server Configuration

# Environment (dev, staging, prod)
environment: "dev"

# AWS Service Configurations
aws:
  # RDS Aurora PostgreSQL Configuration
  rds:
    role_arn: ""
    auth:
      region: "us-west-2"
    host: "your-aurora-cluster.cluster-xxxxxxxxx.us-west-2.rds.amazonaws.com"
    port: 5432
    database: "mcp"
    username: "mcp_admin"
    password: "" # Leave empty when using IAM authentication
    use_iam_auth: true # IAM authentication is the default and recommended method
    token_expiration: 900 # 15 minutes in seconds
    max_open_conns: 25
    max_idle_conns: 5
    conn_max_lifetime: 5m
    enable_pooling: true
    min_pool_size: 2
    max_pool_size: 10
    connection_timeout: 30
  
  # ElastiCache Redis Configuration
  elasticache:
    role_arn: ""
    auth:
      region: "us-west-2"
    primary_endpoint: "your-redis-cluster.xxxxxx.clustercfg.usw2.cache.amazonaws.com"
    port: 6379
    username: "mcp_cache_user"
    password: "" # Leave empty when using IAM authentication
    use_iam_auth: true # IAM authentication is the default and recommended method
    cluster_mode: true
    cluster_name: "mcp-cache"
    cluster_discovery: true
    use_tls: true
    insecure_skip_verify: false # Set to true only for testing
    max_retries: 3
    min_idle_connections: 2
    pool_size: 10
    dial_timeout: 5
    read_timeout: 3
    write_timeout: 3
    pool_timeout: 4
    token_expiration: 900 # 15 minutes in seconds
  
  s3:
    role_arn: ""
    bucket: "mcp-contexts"
    use_iam_auth: true
    region: "us-west-2"
    endpoint: ""
    force_path_style: false
    upload_part_size: 10485760
    download_part_size: 10485760
    concurrency: 10
    request_timeout: 60s
    server_side_encryption: "AES256"

  # Note: S3 Configuration for context storage has been removed as it is no longer supported

# Storage Configuration
# Note: Context storage configurations have been removed as they are no longer supported

# API Server Configuration
api:
  listen_address: ":8080" # For development; use ":443" for production
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
  enable_cors: true
  
  # TLS Configuration (required for production)
  # tls_cert_file: "/certs/tls.crt"
  # tls_key_file: "/certs/tls.key"
  
  # Authentication
  auth:
    jwt_secret: "change-this-to-a-secure-secret"
    api_keys:
      admin: "change-this-to-a-secure-api-key"
      reader: "change-this-to-a-different-secure-api-key"
  
  # Rate Limiting
  rate_limit:
    enabled: true
    limit: 100
    period: 1m
    burst_factor: 3
  
  # Note: Agent Webhook has been removed as it is no longer supported
  
  # Webhook Configuration
  # All webhooks are now configured per tool via the dynamic tools API
  webhooks:
    base_path: "/webhooks"
    # Webhooks are dynamically registered when tools are added

# Database Configuration
database:
  driver: "postgres"
  dsn: "postgres://user:password@localhost:5432/mcp?sslmode=disable" # Used only if not using AWS RDS with IAM auth
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 30m

# Cache Configuration
cache:
  type: "redis"
  address: "localhost:6379" # Used only if not using AWS ElastiCache
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 2
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s

# Core Engine Configuration
engine:
  event_buffer_size: 10000
  concurrency_limit: 10
  event_timeout: 30s
  
  # Security Settings
  security:
    safe_mode: true  # Enable safety checks for all operations
    audit_logging: true  # Log all adapter operations for audit purposes

# Dynamic Tool Configuration
# Tools are now configured via the API, not in static config files
# This section only contains system-wide defaults
dynamic_tools:
  defaults:
    request_timeout: 30s
    retry_max: 3
    retry_delay: 1s
    health_check_interval: 5m
    cache_duration: 5m
  discovery:
    timeout: 30s
    allowed_schemes: ["https"]
    max_redirects: 3
  
  # Mock server configuration for testing
  mock:
    enabled: true
    base_url: "http://mockserver:8081"

# Legacy adapter configuration has been removed
# All tools are now configured dynamically via the API
# See /api/v1/tools endpoints for managing tools

# Monitoring Configuration
monitoring:
  prometheus:
    enabled: true
    path: "/metrics"
  
  logging:
    level: "info"
    format: "json"
    output: "stdout"
    file_path: ""
