# MCP Server Configuration

environment: "dev"

api:
  listen_address: ":8080"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
  enable_cors: true
  auth:
    jwt_secret: "local-test-jwt-secret"
    api_keys:
      admin: "local-admin-api-key"
      reader: "local-reader-api-key"
  rate_limit:
    enabled: true
    limit: 100
    period: 1m
    burst_factor: 3
  webhooks:
    github:
      enabled: true
      path: "/github"
      secret: "change-this-to-a-secure-webhook-secret"

database:
  driver: "postgres"
  dsn: "postgres://postgres:postgres@postgres:5432/mcp?sslmode=disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 30m

cache:
  type: "redis"
  address: "redis:6379"
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 2
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s

engine:
  event_buffer_size: 10000
  concurrency_limit: 10
  event_timeout: 30s
  security:
    safe_mode: true
    audit_logging: true

adapters:
  github:
    api_token: "test-github-token"
    webhook_secret: "test-github-webhook-secret"
    request_timeout: 30s
    retry_max: 3
    retry_delay: 1s
    mock_responses: true
    mock_url: "http://localhost:8081/mock-github"

monitoring:
  prometheus:
    enabled: true
    path: "/metrics"
  logging:
    level: "info"
    format: "json"
    output: "stdout"
    file_path: ""
