# Configuration for GitHub Integration Testing
# This config uses real GitHub API instead of mocks

server:
  listen_address: ":8080"
  enable_cors: true
  enable_metrics: true
  auth:
    jwt_secret: "${JWT_SECRET:-test-secret}"
    api_keys:
      test-key: "admin"

adapters:
  github:
    # Use real GitHub API
    base_url: "${GITHUB_API_URL:-https://api.github.com/}"
    auth:
      token: "${GITHUB_TOKEN}"
      app_id: "${GITHUB_APP_ID}"
      private_key_path: "${GITHUB_APP_PRIVATE_KEY_PATH}"
    webhook:
      secret: "${GITHUB_WEBHOOK_SECRET}"
    # Disable mocks for real API testing
    mock_responses: false
    # Rate limiting for GitHub API
    rate_limit:
      requests_per_hour: 5000
    # Test organization and repository
    test_config:
      organization: "${GITHUB_TEST_ORG}"
      repository: "${GITHUB_TEST_REPO}"
      user: "${GITHUB_TEST_USER}"

database:
  host: "${DB_HOST:-localhost}"
  port: ${DB_PORT:-5432}
  user: "${DB_USER:-mcp_user}"
  password: "${DB_PASSWORD:-mcp_password}"
  name: "${DB_NAME:-mcp_test}"
  ssl_mode: "${DB_SSL_MODE:-disable}"
  schema: "mcp"

cache:
  type: "redis"
  redis:
    addresses:
      - "${REDIS_ADDR:-localhost:6379}"
    password: "${REDIS_PASSWORD:-}"
    db: 0

webhook:
  endpoints:
    github:
      enabled: true
      path: "/webhook/github"
      secret: "${GITHUB_WEBHOOK_SECRET}"

logging:
  level: "debug"
  format: "json"

observability:
  metrics:
    enabled: true
    port: 9090
  tracing:
    enabled: false