# MCP Server Configuration for Local Host Development

environment: "dev"

# API Server Configuration
api:
  listen_address: ":8080"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
  enable_cors: true
  auth:
    jwt_secret: "local-host-jwt-secret"
    api_keys:
      admin: "local-host-admin-api-key"
      reader: "local-host-reader-api-key"
  rate_limit:
    enabled: true
    limit: 100
    period: 1m
    burst_factor: 3
  webhooks:
    github:
      enabled: true
      path: "/github"
      secret: "local-host-github-webhook-secret"

# Database Configuration
database:
  driver: "postgres"
  dsn: "postgres://postgres:postgres@localhost:5432/mcp?sslmode=disable"
  max_open_conns: 10
  max_idle_conns: 2
  conn_max_lifetime: 30m

# Cache Configuration
cache:
  type: "redis"
  address: "localhost:6379"
  password: ""
  db: 0
  pool_size: 5
  min_idle_conns: 1
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s

# Monitoring Configuration
monitoring:
  prometheus:
    enabled: true
    path: "/metrics"
  logging:
    level: "debug"
    format: "json"
    output: "stdout"
    file_path: ""

# Core Engine Configuration
engine:
  event_buffer_size: 1000
  concurrency_limit: 5
  event_timeout: 30s
  security:
    safe_mode: true
    audit_logging: true

# DevOps Tool Adapters
adapters:
  github:
    api_token: "local-host-github-token"
    webhook_secret: "local-host-github-webhook-secret"
    request_timeout: 30s
    retry_max: 3
    retry_delay: 1s
    mock_responses: true
    mock_url: "http://localhost:8081/mock-github"
    github:
      enabled: true
      secret: "mock-github-secret"
      path: "/github"

# Database Configuration
database:
  driver: "postgres"
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  database: "mcp"
  ssl_mode: "disable"
  dsn: "postgres://postgres:postgres@localhost:5432/mcp?sslmode=disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 5m

# Cache Configuration
cache:
  type: "redis"
  address: "localhost:6379"
  password: ""
  database: 0
  use_iam_auth: false
  max_retries: 3
  dial_timeout: 5
  read_timeout: 3
  write_timeout: 3
  pool_size: 10
  min_idle_conns: 2
  pool_timeout: 4

# Core Engine Configuration
engine:
  event_buffer_size: 1000
  concurrency_limit: 5
  event_timeout: 30s
  
  # GitHub Configuration
  github:
    api_token: "mock-github-token"
    webhook_secret: "mock-github-secret"
    request_timeout: 10s
    rate_limit_per_hour: 5000
    max_retries: 3
    retry_delay: 1s
    mock_responses: true
    mock_url: "http://localhost:8081/mock-github"

  # Harness Configuration
  harness:
    api_token: "mock-harness-token"
    account_id: "mock-account-id"
    request_timeout: 10s
    max_retries: 3
    retry_delay: 1s
    mock_responses: true
    mock_url: "http://localhost:8081/mock-harness"
    
  # SonarQube Configuration
  sonarqube:
    token: "mock-sonarqube-token"
    request_timeout: 10s
    max_retries: 3
    retry_delay: 1s
    mock_responses: true
    mock_url: "http://localhost:8081/mock-sonarqube"
    
  # Artifactory Configuration
  artifactory:
    token: "mock-artifactory-token"
    request_timeout: 10s
    max_retries: 3
    retry_delay: 1s
    mock_responses: true
    mock_url: "http://localhost:8081/mock-artifactory"
    
  # Xray Configuration
  xray:
    token: "mock-xray-token"
    request_timeout: 10s
    max_retries: 3
    retry_delay: 1s
    mock_responses: true
    mock_url: "http://localhost:8081/mock-xray"

# Metrics Configuration
metrics:
  enabled: false
  type: "prometheus"
  endpoint: ""
  push_gateway: ""
  push_interval: 10s