name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'
          
      - name: Run linter
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          make lint

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'
          
      - name: Run gosec
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          make security-checks

  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    # Only run Docker builds on push, not on PRs
    if: github.event_name == 'push'
    strategy:
      matrix:
        app: [mcp-server, rest-api, worker, mockserver]
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Docker info
        run: |
          docker version
          docker buildx version
          docker buildx ls
          
      - name: Debug environment
        run: |
          echo "=== Go environment ==="
          which go || echo "Go not installed"
          go version || echo "Go version failed"
          echo "=== Directory structure ==="
          ls -la
          ls -la apps/
          echo "=== go.work contents ==="
          cat go.work
          echo "=== go.mod files ==="
          find . -name "go.mod" -type f
          
      - name: Build Docker image
        run: |
          echo "Building ${{ matrix.app }}..."
          docker build --progress=plain -f apps/${{ matrix.app }}/Dockerfile -t ${{ matrix.app }}:test . 2>&1 || {
            echo "Docker build failed with exit code $?"
            exit 1
          }