name: Deploy Swagger Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/swagger/**'
      - '.github/workflows/deploy-swagger-docs.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install -g @apidevtools/swagger-cli
          
      - name: Validate OpenAPI spec
        run: |
          swagger-cli validate docs/swagger/openapi.yaml
          
      - name: Build Swagger UI
        run: |
          # Configuration
          BUILD_DIR="build/swagger-docs"
          OPENAPI_SPEC="docs/swagger/openapi.yaml"
          SWAGGER_UI_VERSION="5.27.0"
          SWAGGER_UI_DIST_URL="https://unpkg.com/swagger-ui-dist@${SWAGGER_UI_VERSION}/"
          
          # Create build directory
          rm -rf "$BUILD_DIR"
          mkdir -p "$BUILD_DIR"
          
          # Download Swagger UI files
          cd "$BUILD_DIR"
          FILES=(
              "swagger-ui.css"
              "swagger-ui-bundle.js"
              "swagger-ui-standalone-preset.js"
              "favicon-16x16.png"
              "favicon-32x32.png"
          )
          
          for file in "${FILES[@]}"; do
              curl -s -L -o "$file" "${SWAGGER_UI_DIST_URL}${file}"
          done
          
          cd ../..
          
          # Copy OpenAPI spec and referenced files
          cp "$OPENAPI_SPEC" "$BUILD_DIR/openapi.yaml"
          cp -r docs/swagger/. "$BUILD_DIR/swagger/"
          
          # Create custom index.html
          cat > "$BUILD_DIR/index.html" << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <title>Developer Mesh API Documentation</title>
              <link rel="stylesheet" type="text/css" href="./swagger-ui.css" />
              <link rel="icon" type="image/png" href="./favicon-32x32.png" sizes="32x32" />
              <link rel="icon" type="image/png" href="./favicon-16x16.png" sizes="16x16" />
              <style>
                  html {
                      box-sizing: border-box;
                      overflow: -moz-scrollbars-vertical;
                      overflow-y: scroll;
                  }
                  *, *:before, *:after {
                      box-sizing: inherit;
                  }
                  body {
                      margin: 0;
                      background: #fafafa;
                  }
                  .swagger-ui .topbar {
                      background-color: #1a1a1a;
                  }
                  .swagger-ui .topbar .download-url-wrapper .download-url-button {
                      background: #4CAF50;
                      color: white;
                  }
                  .swagger-ui .topbar .download-url-wrapper .download-url-button:hover {
                      background: #45a049;
                  }
                  /* Hide the confusing URL input field and only show the title */
                  .swagger-ui .topbar .download-url-wrapper {
                      display: none !important;
                  }
                  /* Add a custom header message */
                  .swagger-ui .topbar::after {
                      content: "Developer Mesh API Documentation";
                      color: white;
                      font-size: 20px;
                      font-weight: 600;
                      position: absolute;
                      left: 50%;
                      top: 50%;
                      transform: translate(-50%, -50%);
                  }
              </style>
          </head>
          <body>
              <div id="swagger-ui"></div>
              <script src="./swagger-ui-bundle.js" charset="UTF-8"></script>
              <script src="./swagger-ui-standalone-preset.js" charset="UTF-8"></script>
              <script>
                  window.onload = function() {
                      window.ui = SwaggerUIBundle({
                          url: "./swagger/openapi.yaml",
                          dom_id: '#swagger-ui',
                          deepLinking: true,
                          presets: [
                              SwaggerUIBundle.presets.apis,
                              SwaggerUIStandalonePreset
                          ],
                          plugins: [
                              SwaggerUIBundle.plugins.DownloadUrl
                          ],
                          layout: "StandaloneLayout",
                          defaultModelsExpandDepth: 1,
                          defaultModelExpandDepth: 1,
                          docExpansion: "list",
                          filter: true,
                          showExtensions: true,
                          showCommonExtensions: true,
                          tryItOutEnabled: true,
                          supportedSubmitMethods: ['get', 'post', 'put', 'delete', 'patch'],
                          onComplete: function() {
                              console.log("Swagger UI loaded successfully");
                          },
                          validatorUrl: null
                      });
                  };
              </script>
          </body>
          </html>
          EOF
          
          # Create 404 page
          cat > "$BUILD_DIR/404.html" << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <title>404 - Page Not Found</title>
              <meta http-equiv="refresh" content="0; url=/" />
              <style>
                  body {
                      font-family: Arial, sans-serif;
                      text-align: center;
                      padding: 50px;
                  }
              </style>
          </head>
          <body>
              <h1>404 - Page Not Found</h1>
              <p>Redirecting to the API documentation...</p>
              <p>If you are not redirected, <a href="/">click here</a>.</p>
          </body>
          </html>
          EOF
          
          # Create CNAME file for custom domain
          echo "docs.dev-mesh.io" > "$BUILD_DIR/CNAME"
          
          # Create .nojekyll file to prevent Jekyll processing
          touch "$BUILD_DIR/.nojekyll"
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/swagger-docs'
          
  deploy:
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4