name: Release

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io

jobs:
  release:
    name: Build and Push
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        app: [mcp-server, rest-api, worker, mockserver]
    steps:
      - uses: actions/checkout@v4
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        run: |
          # Get the tag name
          TAG=${GITHUB_REF#refs/tags/}
          
          # Build and push with version tag
          docker build -f apps/${{ matrix.app }}/Dockerfile -t ${{ env.REGISTRY }}/${{ github.repository_owner }}/devops-mcp-${{ matrix.app }}:$TAG .
          docker push ${{ env.REGISTRY }}/${{ github.repository_owner }}/devops-mcp-${{ matrix.app }}:$TAG
          
          # Also tag as latest
          docker tag ${{ env.REGISTRY }}/${{ github.repository_owner }}/devops-mcp-${{ matrix.app }}:$TAG ${{ env.REGISTRY }}/${{ github.repository_owner }}/devops-mcp-${{ matrix.app }}:latest
          docker push ${{ env.REGISTRY }}/${{ github.repository_owner }}/devops-mcp-${{ matrix.app }}:latest

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## Docker Images
            
            The following images have been published:
            - `ghcr.io/${{ github.repository_owner }}/devops-mcp-mcp-server:${{ github.ref_name }}`
            - `ghcr.io/${{ github.repository_owner }}/devops-mcp-rest-api:${{ github.ref_name }}`
            - `ghcr.io/${{ github.repository_owner }}/devops-mcp-worker:${{ github.ref_name }}`
            - `ghcr.io/${{ github.repository_owner }}/devops-mcp-mockserver:${{ github.ref_name }}`
          draft: false
          prerelease: false